config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :profiles

  resources :chat_rooms
  resources :categories
  resources :qr_teches
  resources :snoopers
  resources :events
  

  #get 'profiles/edit', as: 'user_root'

  # For details on the DSL available within this file, see nrails.org/routing.html
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :profile
	has_and_belongs_to_many :event
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
	belongs_to :event
	has_and_belongs_to_many :profiles
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
	belongs_to :profile
	has_and_belongs_to_many :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :profile
	has_one :snooper
	has_and_belongs_to_many :categories
	has_many :chat_rooms
	has_many :invites
	has_and_belongs_to_many :check_ins
	belongs_to :qr_invite, class_name: 'QrTech', foreign_key: 'qr_invite_id',  optional: true
	belongs_to :qr_checkin, class_name: 'QrTech', foreign_key: 'qr_checkin_id',  optional: true
	
	geocoded_by :contacts
	after_validation :geocode
  	scope :search, lambda {|query| where('title LIKE ?', "%#{query}%")}

  def self.per_page
	  3
	end

end

app/models/invite.rb
class Invite < ApplicationRecord
 belongs_to :profiles
 belongs_to :event
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user, optional: true
	has_many :events
	has_many :invites
	has_many :check_ins
	has_and_belongs_to_many :categories
	has_and_belongs_to_many :chat_rooms
end

app/models/qr_tech.rb
class QrTech < ApplicationRecord
	has_many :events
end

app/models/snooper.rb
class Snooper < ApplicationRecord
	has_and_belongs_to_many :event, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :create_user_profile

  def create_user_profile
  	(self.profile = Profile.new).save!
  end
end


# (user_name: @user[:name])

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @page = params[:page] ? params[:page] : 1
    @filter = EventsFilter.new(params[:filter])
    if params[:filter]
      #init Filter Object 
      @events = @filter.records
    else
      @events = Event.all
    end
    @events = @events.paginate(:page => @page, per_page: Event.per_page)
    if params[:ajax]
      render partial: "list.html", locals: {events: @events }
    else
      render
    end
  end

  def show
  end

  def new
    if current_user.profile.user_name.blank?
      redirect_to edit_profile_path(current_user.id), notice: 'Заполните ваш профиль перед созданием нового EVENT.'
    else
      @event = Event.new
    end
  end

  def edit
  end

  def create
    @event = Event.new(event_params.merge(profile_id: current_user.profile.id))
    @event.author = current_user.profile.user_name
    @event.save
    if @event.save
      respond_to do |format|
        format.html {redirect_to @event, notice: 'Event was successfully created.'}
        format.json {render text: 'Yee!'}
      end
    else
      render :edit
    end
  end

  def update
    if @event.update(event_params)
      respond_to do |format|
        format.html { redirect_to @event, notice: 'Event was successfully updated.'}
        format.json { render json: {a: 'Yee!'}}
      end
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def append_cur_location
      unless @lat_lng.blank?
        @hash << { :lat=>@lat_lng[0], :lng=>@lat_lng[1]}
      end   
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:author, :title, :description, :date_time, :latitude, :longitude, :private, :contacts, :category_ids => [])
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # # GET /users
  # # GET /users.json
  # def index
  #   @users = User.all
  # end

  # GET /users/1
  # GET /users/1.json
  def show
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        redirect_to @user.profile, notice: 'User was successfully created.'
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/qr_teches_helper.rb
module QrTechesHelper
end

app/helpers/snoopers_helper.rb
module SnoopersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_category_checkbox.html.haml
.filter_options_container
  %fieldset.filter_form_fieldset
    - Category.all.each do |category|
      %label.category_check{:for => "category-#{category.id}"}
        = check_box_tag 'filter[categories][]', category.id, @filter.has_category?(category.id.to_s), :id => "category-#{category.id}"
        = category.name
        

app/views/events/_form.html.haml
.mdl-textfield.mdl-js-textfield
  = form_with(model: event, local: true, id: "test") do |form|
    - if event.errors.any?
      #error_explanation
        %h2
          = pluralize(event.errors.count, "error")
          prohibited this event from being saved:
        %ul
          - event.errors.full_messages.each do |message|
            %li= message

    .field
      = form.label :title, "Название", class: "mdl-textfield__label"
      = form.text_field :title, id: :event_title, class: "mdl-textfield__input"
    .field
      = form.label :description, "Описание"
      = form.text_field :description, id: :event_description
    .field
      = form.label :date_time, "Дата мероприятия"
      = form.text_field :date_time, id: :event_date_time
    .field
      = form.label :latitude, "Широта"
      = form.text_field :latitude, id: :event_latitude  
    .field
      = form.label :longitude, "Долгота"
      = form.text_field :longitude, id: :event_longitude
    .field
      = form.radio_button(:private, 'false')
      = form.label(:private_false, 'Публичное мероприятие')
      = form.radio_button(:private, 'true')
      = form.label(:private_true, 'Приватное мероприятие')
    .field
      = form.label :contacts, "Контакты"
      = form.text_field :contacts, id: :event_contacts
    .field
      = form.select :category_ids, options_for_select(Category.all.map {|category| [category.name, category.id]}, event.category_ids), {}, :multiple => true
    .actions
      = form.submit

app/views/events/_list.html.haml
%section#fixed-tab-1.mdl-layout__tab-panel.is-active
  .page-content
    %h2 Все события        
    .materialContainer
      %table.mdl-data-table.mdl-js-data-table
        %thead
          %tr
            %th.mdl-data-table__cell--non-numeric Создатель
            %th.mdl-data-table__cell--non-numeric Название
            %th.mdl-data-table__cell--non-numeric Описание
            %th.mdl-data-table__cell--non-numeric Дата события
            %th.mdl-data-table__cell--non-numeric Адрес
            %th.mdl-data-table__cell--non-numeric{:colspan => "3"}
        %tbody
          - @events.each do |event|
            %tr
              %td.mdl-data-table__cell--non-numeric= event.author
              %td.mdl-data-table__cell--non-numeric= link_to "#{event.title}", event
              %td.mdl-data-table__cell--non-numeric= event.description
              %td.mdl-data-table__cell--non-numeric= event.date_time
              %td.mdl-data-table__cell--non-numeric= event.contacts
              %td.mdl-data-table__cell--non-numeric= link_to ('<i class="material-icons">edit</i>').html_safe, edit_event_path(event)
              %td.mdl-data-table__cell--non-numeric= link_to ('<i class="material-icons">delete</i>').html_safe, event, method: :delete, data: { confirm: 'Are you sure?' }
              
    -if user_signed_in?
      = link_to 'Новое событие', new_event_path

app/views/events/_search.html.haml
.mdl-textfield.mdl-js-textfield.mdl-textfield--expandable.mdl-textfield--floating-label.mdl-textfield--align-right
  %label.mdl-button.mdl-js-button.mdl-button--icon{:for => "fixed-header-drawer-exp"}
    %i.material-icons search
  .mdl-textfield__expandable-holder
    = text_field_tag "#{resourse}[query]", value, id: 'fixed-header-drawer-exp', class: "mdl-textfield__input"

app/views/events/edit.html.haml
%h1 Редактирование события
= render 'form', event: @event
= link_to 'Событие', @event
|
= link_to 'Все события', events_path

app/views/events/index.html.haml
.mdl-layout.mdl-js-layout.mdl-layout--fixed-header.mdl-layout--fixed-tabs
  %header.mdl-layout__header
    .mdl-layout__header-row      
    / Tabs
    .mdl-layout__tab-bar.mdl-js-ripple-effect
      %a.mdl-layout__tab.is-active{:href => "#fixed-tab-1"} Список
      %a.mdl-layout__tab{:href => "#fixed-tab-2"} Карта
  .mdl-layout__drawer
    %span.mdl-layout-title Фильтр
    = form_tag events_path, method: "get", remote: true, id: "search_form" do
      = render partial: "search", locals: {resourse: "filter", value: @filter.params[:query]}
      = render partial: "category_checkbox"
      .filter_form_button
        %p2
          %input{:type => "submit", :value => "Filter", name: nil}


      / = f.check_box "Categories"
    / = collection_check_boxes(:event, :categiry_ids, Category.first(5), :id, :name)


  %main.mdl-layout__content
    = render 'list', locals: {events: @events}
    = will_paginate @events

    %section#fixed-tab-2.mdl-layout__tab-panel
      .page-content
        / Your content goes here
      #map{style: 'width: 800px; height: 500px;'}

      :javascript
        Event.MapBuilder.init_map();
        


:javascript
  FilterBehaviour.init("#search_form");

app/views/events/new.html.haml
%h1 Новое событие
= render 'form', event: @event
= link_to 'Назад', events_path

app/views/events/show.html.haml
.mdl-grid
  .mdl-cell.mdl-cell--8-col

    %p#notice= notice
    %p
      %strong Author:
      = @event.author
    %p
      %strong Title:
      = @event.title
    %p
      %strong Description:
      = @event.description
    %p
      %strong Date time:
      = @event.date_time
    %p
      %strong Latitude:
      = @event.latitude
    %p
      %strong Longitude:
      = @event.longitude
    %p
      %strong Private:
      = @event.private
    %p
      %strong Категории:
      - @event.categories.each do |category|
        = category.name

    = link_to ('<i class="material-icons">edit</i>').html_safe, edit_event_path(@event)

    .map{style: 'width: 800px;'}
      #map{style: 'width: 800px; height: 400px;'}

      :javascript
        Event.MapBuilder.init_map();

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :email
    = form.text_field :email, id: :user_email
  .actions
    = form.submit

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user
= link_to 'Show', @user
|
= link_to 'Back', users_path

app/views/users/new.html.haml
%h1 New User
= render 'form', user: @user
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %strong Email:
  = @user.email
= link_to 'Edit', edit_user_path(@user)
|
= link_to 'My profile', profile_path