config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :profiles

  resources :chat_rooms
  resources :categories
  resources :qr_teches
  resources :snoopers
  resources :events
  

  #get 'profiles/edit', as: 'user_root'

  # For details on the DSL available within this file, see nrails.org/routing.html
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :profile
	has_and_belongs_to_many :event
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
	belongs_to :event
	has_and_belongs_to_many :profiles
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
	belongs_to :profile
	has_and_belongs_to_many :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :profile
	has_one :snooper
	has_and_belongs_to_many :categories
	has_many :chat_rooms
	has_many :invites
	has_and_belongs_to_many :check_ins
	belongs_to :qr_invite, class_name: 'QrTech', foreign_key: 'qr_invite_id',  optional: true
	belongs_to :qr_checkin, class_name: 'QrTech', foreign_key: 'qr_checkin_id',  optional: true
	
	geocoded_by :contacts
	after_validation :geocode
  	scope :search, lambda {|query| where('title LIKE ?', "%#{query}%")}

  def self.per_page
	  3
	end

end

app/models/invite.rb
class Invite < ApplicationRecord
 belongs_to :profiles
 belongs_to :event
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user, optional: true
	has_many :events
	has_many :invites
	has_many :check_ins
	has_and_belongs_to_many :categories
	has_and_belongs_to_many :chat_rooms
end

app/models/qr_tech.rb
class QrTech < ApplicationRecord
	has_many :events
end

app/models/snooper.rb
class Snooper < ApplicationRecord
	has_and_belongs_to_many :event, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :create_user_profile

  def create_user_profile
  	(self.profile = Profile.new).save!
  end
end


# (user_name: @user[:name])

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @page = params[:page] ? params[:page] : 1
    @filter = EventsFilter.new(params[:filter])
    if params[:filter]
      #init Filter Object 
      @events = @filter.records
    else
      @events = Event.all
    end
    @events = @events.paginate(:page => @page, per_page: Event.per_page)
    if params[:ajax]
      render partial: "list.html", locals: {events: @events }
    else
      render
    end
  end

  def show
  end

  def new
    if current_user.profile.user_name.blank?
      redirect_to edit_profile_path(current_user.id), notice: 'Заполните ваш профиль перед созданием нового EVENT.'
    else
      @event = Event.new
    end
  end

  def edit
  end

  def create
    @event = Event.new(event_params.merge(profile_id: current_user.profile.id))
    @event.author = current_user.profile.user_name
    @event.save
    if @event.save
      respond_to do |format|
        format.html {redirect_to @event, notice: 'Event was successfully created.'}
        format.json {render text: 'Yee!'}
      end
    else
      render :edit
    end
  end

  def update
    if @event.update(event_params)
      respond_to do |format|
        format.html { redirect_to @event, notice: 'Event was successfully updated.'}
        format.json { render json: {a: 'Yee!'}}
      end
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def append_cur_location
      unless @lat_lng.blank?
        @hash << { :lat=>@lat_lng[0], :lng=>@lat_lng[1]}
      end   
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:author, :title, :description, :date_time, :latitude, :longitude, :private, :contacts, :category_ids => [])
    end
end

app/controllers/qr_teches_controller.rb
class QrTechesController < ApplicationController
  before_action :set_qr_tech, only: [:show, :edit, :update, :destroy]

  # GET /qr_teches
  # GET /qr_teches.json
  def index
    @qr_teches = QrTech.all
  end

  # GET /qr_teches/1
  # GET /qr_teches/1.json
  def show
  end

  # GET /qr_teches/new
  def new
    @qr_tech = QrTech.new
  end

  # GET /qr_teches/1/edit
  def edit
  end

  # POST /qr_teches
  # POST /qr_teches.json
  def create
    @qr_tech = QrTech.new(qr_tech_params)

    respond_to do |format|
      if @qr_tech.save
        format.html { redirect_to @qr_tech, notice: 'Qr tech was successfully created.' }
        format.json { render :show, status: :created, location: @qr_tech }
      else
        format.html { render :new }
        format.json { render json: @qr_tech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qr_teches/1
  # PATCH/PUT /qr_teches/1.json
  def update
    respond_to do |format|
      if @qr_tech.update(qr_tech_params)
        format.html { redirect_to @qr_tech, notice: 'Qr tech was successfully updated.' }
        format.json { render :show, status: :ok, location: @qr_tech }
      else
        format.html { render :edit }
        format.json { render json: @qr_tech.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qr_teches/1
  # DELETE /qr_teches/1.json
  def destroy
    @qr_tech.destroy
    respond_to do |format|
      format.html { redirect_to qr_teches_url, notice: 'Qr tech was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qr_tech
      @qr_tech = QrTech.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qr_tech_params
      params.fetch(:qr_tech, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # # GET /users
  # # GET /users.json
  # def index
  #   @users = User.all
  # end

  # GET /users/1
  # GET /users/1.json
  def show
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        redirect_to @user.profile, notice: 'User was successfully created.'
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/qr_teches_helper.rb
module QrTechesHelper
end

app/helpers/snoopers_helper.rb
module SnoopersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/qr_teches/_form.html.erb
<%= form_with(model: qr_tech, local: true) do |form| %>
  <% if qr_tech.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qr_tech.errors.count, "error") %> prohibited this qr_tech from being saved:</h2>

      <ul>
      <% qr_tech.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/qr_teches/_form.html.haml
= form_with(model: qr_tech, local: true) do |form|
  - if qr_tech.errors.any?
    #error_explanation
      %h2
        = pluralize(qr_tech.errors.count, "error")
        prohibited this qr_tech from being saved:
      %ul
        - qr_tech.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/qr_teches/edit.html.erb
<h1>Editing Qr Tech</h1>

<%= render 'form', qr_tech: @qr_tech %>

<%= link_to 'Show', @qr_tech %> |
<%= link_to 'Back', qr_teches_path %>

app/views/qr_teches/edit.html.haml
%h1 Editing Qr Tech
= render 'form', qr_tech: @qr_tech
= link_to 'Show', @qr_tech
|
= link_to 'Back', qr_teches_path

app/views/qr_teches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qr Teches</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qr_teches.each do |qr_tech| %>
      <tr>
        <td><%= link_to 'Show', qr_tech %></td>
        <td><%= link_to 'Edit', edit_qr_tech_path(qr_tech) %></td>
        <td><%= link_to 'Destroy', qr_tech, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qr Tech', new_qr_tech_path %>

app/views/qr_teches/index.html.haml
%p#notice= notice
%h1 Qr Teches
%table
  %thead
    %tr
      %th{:colspan => "3"}
  %tbody
    - @qr_teches.each do |qr_tech|
      %tr
        %td= link_to 'Show', qr_tech
        %td= link_to 'Edit', edit_qr_tech_path(qr_tech)
        %td= link_to 'Destroy', qr_tech, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Qr Tech', new_qr_tech_path

app/views/qr_teches/new.html.erb
<h1>New Qr Tech</h1>

<%= render 'form', qr_tech: @qr_tech %>

<%= link_to 'Back', qr_teches_path %>

app/views/qr_teches/new.html.haml
%h1 New Qr Tech
= render 'form', qr_tech: @qr_tech
= link_to 'Back', qr_teches_path

app/views/qr_teches/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_qr_tech_path(@qr_tech) %> |
<%= link_to 'Back', qr_teches_path %>

app/views/qr_teches/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_qr_tech_path(@qr_tech)
|
= link_to 'Back', qr_teches_path