config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :profiles

  resources :chat_rooms
  resources :categories
  resources :qr_teches
  resources :snoopers
  resources :events
  

  #get 'profiles/edit', as: 'user_root'

  # For details on the DSL available within this file, see nrails.org/routing.html
  root to: "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :profile
	has_and_belongs_to_many :event
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
	belongs_to :event
	has_and_belongs_to_many :profiles
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
	belongs_to :profile
	has_and_belongs_to_many :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :profile
	has_one :snooper
	has_and_belongs_to_many :categories
	has_many :chat_rooms
	has_many :invites
	has_and_belongs_to_many :check_ins
	belongs_to :qr_invite, class_name: 'QrTech', foreign_key: 'qr_invite_id',  optional: true
	belongs_to :qr_checkin, class_name: 'QrTech', foreign_key: 'qr_checkin_id',  optional: true
	
	geocoded_by :contacts
	after_validation :geocode
  	scope :search, lambda {|query| where('title LIKE ?', "%#{query}%")}

  def self.per_page
	  3
	end

end

app/models/invite.rb
class Invite < ApplicationRecord
 belongs_to :profiles
 belongs_to :event
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user, optional: true
	has_many :events
	has_many :invites
	has_many :check_ins
	has_and_belongs_to_many :categories
	has_and_belongs_to_many :chat_rooms
end

app/models/qr_tech.rb
class QrTech < ApplicationRecord
	has_many :events
end

app/models/snooper.rb
class Snooper < ApplicationRecord
	has_and_belongs_to_many :event, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :create_user_profile

  def create_user_profile
  	(self.profile = Profile.new).save!
  end
end


# (user_name: @user[:name])

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/qr_teches_helper.rb
module QrTechesHelper
end

app/helpers/snoopers_helper.rb
module SnoopersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EventProject
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAIvB_rZxPifLuLn6d9_mGZilXNipDnCos&callback=Event.MapBuilder.init_map"
  %body

  %p#notice= notice
  .devise
  - if user_signed_in?
    %span Здравствуйте,
    = current_user.profile.user_name
    = link_to 'Выйти', destroy_user_session_path, method: :delete, data: { confirm: 'Вы точно хотите выйти?' }
  - else    
    = link_to 'Войти', new_user_session_path
    %span или
    = link_to 'Зарегистрироваться', new_user_registration_path

  .block_panel
    %tr= link_to 'Главная', root_path
    %tr= link_to 'Профиль', profile_path(current_user.profile.id) if user_signed_in?
    %tr= link_to 'Категории', categories_path
    %tr= link_to 'Чаты', chat_rooms_path
    %tr= link_to 'QR code', qr_teches_path
    %tr= link_to 'Ищейка', snoopers_path
  = yield
  
- unless @lat_lng
  :javascript
    Get.GeoLocation.init();